api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    title: 'The API of the UTT student website'
    description: "The API that allows to interact with the database of the student site to consult, modify and delete some data according to the user's access."
    version: '%env(APP_VERSION)%'

    # Set this to false if you want Webby to disappear. Webby is the spider at the left of the swagger interface.
    show_webby: false
