version: '3'
services:
  application:
    image: ungdev/etuutt-api
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8000:8080"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      TZ: Europe/Paris

  database:
    image: "mariadb:10.11"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 2s
      retries: 120
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abcdef
      MYSQL_DATABASE: etuutt
      MYSQL_USER: etuutt
      MYSQL_PASSWORD: abcdef
      MARIADB_MYSQL_LOCALHOST_USER: true

volumes:
  database-data:
