version: '3'

services:
  application:
    image: larueli/php-symfony-base-image:8.2
    user: "1000:0"
    environment:
      DATABASE_URL: "mysql://etuutt:abcdef@database:3306/etuutt?serverVersion=mariadb-10.11.2&charset=utf8"
      MAILER_DSN: "smtp://mailer:1025"
    volumes:
      - ./:/var/www/html

  # database:
  #   ports:
  #     - "3306:3306"

  adminer:
    restart: always
    image: adminer
    environment:
      ADMINER_DEFAULT_DB_HOST: database
      ADMINER_DEFAULT_DB_NAME: etuutt
      ADMINER_DESIGN: lucas-sandery
    ports:
      - "8080:8080"

  mailer:
    restart: always
    image: sj26/mailcatcher
    ports:
      - "1025"
      - "1080:1080"