version: '3'
services:
  application:
    image: larueli/php-symfony-base-image
    depends_on:
      - database
    ports:
      - "8000:8080"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      TZ: Europe/Paris
      WAIT_HOSTS: "database:3306"

  database:
    image: "mariadb:10.6"
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abcdef
      MYSQL_DATABASE: etuutt
      MYSQL_USER: etuutt
      MYSQL_PASSWORD: abcdef

volumes:
  database-data:
