version: '3'
services:
  application:
    image: ungdev/etuutt-api
    depends_on:
      database:
        condition: service_healthy
    networks:
      - traefik
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      TZ: Europe/Paris
    labels:
      - "traefik.http.routers.etuutt_api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.services.etuutt_api.loadbalancer.server.port=8080"
      - "traefik.http.routers.etuutt_api.middlewares=etuutt_api_strip"
      - "traefik.http.middlewares.etuutt_api.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.etuutt_api.stripprefix.forceslash=false"

  database:
    image: "mariadb:10.11"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 2s
      retries: 120
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abcdef
      MYSQL_DATABASE: etuutt
      MYSQL_USER: etuutt
      MYSQL_PASSWORD: abcdef
      MARIADB_MYSQL_LOCALHOST_USER: true

volumes:
  database-data:
