version: '3'
services:
  application:
    image: ghcr.io/ungdev/etuutt-api:master
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
      - traefik
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      TZ: Europe/Paris
    labels:
      - "traefik.http.routers.etuutt_api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.services.etuutt_api.loadbalancer.server.port=8080"
      - "traefik.http.routers.etuutt_api.middlewares=etuutt_api_strip"
      - "traefik.http.middlewares.etuutt_api_strip.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.etuutt_api_strip.stripprefix.forceslash=false"
      - "traefik.docker.network=traefik"

  database:
    image: "mariadb:10.11"
    healthcheck:
      test: ["CMD-SHELL", "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'  || exit 1"]
      interval: 5s
      retries: 10
    networks:
      - default
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abcdef
      MYSQL_DATABASE: etuutt
      MYSQL_USER: etuutt
      MYSQL_PASSWORD: abcdef

volumes:
  database-data:

networks:
  traefik:
    external: true